2023-10-15 23:26:28+01:00

diff --git a/world/diffs/gnome-remote-desktop.diff b/world/diffs/gnome-remote-desktop.diff
--- a/world/diffs/gnome-remote-desktop.diff
+++ b/world/diffs/gnome-remote-desktop.diff
@@ -1,53 +1,30 @@
 --- Arch PKGBUILD
 +++ Artix PKGBUILD
-@@ -1,6 +1,6 @@
- 
- pkgname=gnome-remote-desktop
--pkgver=45.0
-+pkgver=44.2
- pkgrel=1
- pkgdesc="GNOME Remote Desktop server"
- url="https://wiki.gnome.org/Projects/Mutter/RemoteDesktop"
-@@ -13,16 +13,13 @@
-   fuse3
-   glib2
-   libdrm
--  libei
-   libepoxy
-   libfdk-aac
-   libnotify
--  libpipewire
-   libsecret
+@@ -22,8 +22,8 @@
    libvncserver
    libxkbcommon
    pipewire
 -  systemd
    tpm2-tss
++  wireplumber
  )
  makedepends=(
-@@ -32,15 +29,14 @@
-   meson
- )
- checkdepends=(
--  dbus-broker
--  libegl
+   asciidoc
+@@ -37,7 +37,7 @@
    mutter
    python-dbus
    python-gobject
-   wireplumber
+-  wireplumber
++  pipewire-alsa
  )
  groups=(gnome)
--_commit=a7c4f2dd87fe09389dd93268b0ce3e32a6ceb6eb  # tags/45.0^0
-+options=(debug)
-+_commit=9d1ee9c9458636dbe4d3326dceec81dfefef56dd  # tags/44.2^0
- source=("git+https://gitlab.gnome.org/GNOME/gnome-remote-desktop.git#commit=$_commit")
- b2sums=('SKIP')
+ _commit=a7c4f2dd87fe09389dd93268b0ce3e32a6ceb6eb  # tags/45.0^0
+@@ -55,15 +55,16 @@
  
-@@ -56,14 +52,45 @@
  build() {
    local meson_options=(
-     -D vnc=true
 +    -D systemd=false
+     -D vnc=true
    )
  
 -  arch-meson $pkgname build "${meson_options[@]}"
@@ -55,39 +32,9 @@
    meson compile -C build
  }
  
-+_check() (
-+  export XDG_CONFIG_HOME="$PWD/config-dir" XDG_RUNTIME_DIR="$PWD/runtime-dir"
-+  mkdir -p -m 700 "$XDG_CONFIG_HOME" "$XDG_RUNTIME_DIR"
-+
-+  export GSETTINGS_SCHEMA_DIR="$PWD/build/src" GSETTINGS_BACKEND=keyfile
-+  glib-compile-schemas "$GSETTINGS_SCHEMA_DIR"
-+
-+  openssl req -new -newkey rsa:4096 -days 720 -nodes -x509 \
-+    -subj /C=DE/ST=NONE/L=NONE/O=GNOME/CN=gnome.org \
-+    -keyout tls.key -out tls.crt
-+
-+  gsettings set org.gnome.desktop.remote-desktop.rdp tls-cert "$PWD/tls.crt"
-+  gsettings set org.gnome.desktop.remote-desktop.rdp tls-key "$PWD/tls.key"
-+  gsettings set org.gnome.desktop.remote-desktop.rdp screen-share-mode extend
-+  gsettings set org.gnome.desktop.remote-desktop.rdp enable true
-+  gsettings set org.gnome.desktop.remote-desktop.vnc enable true
-+
-+  pipewire &
-+  _p1=$!
-+
-+  wireplumber &
-+  _p2=$!
-+
-+  trap "kill $_p1 $_p2; wait" EXIT
-+
-+  export TCTI=tabrmd:bus_type=session
-+
-+  meson test -C build --print-errorlogs -t 3
-+)
-+
  check() {
 -  meson test -C build --print-errorlogs -t 3
-+  dbus-run-session bash -c "$(declare -f _check); _check" || :
++  meson test -C build --print-errorlogs -t 3 ||: # test fails skip
  }
  
  package() {
@@ -97,37 +44,24 @@
 
 --- Arch PKGBUILD
 +++ Artix PKGBUILD
-@@ -6,16 +6,13 @@
-   fuse3
-   glib2
-   libdrm
--  libei
-   libepoxy
-   libfdk-aac
-   libnotify
--  libpipewire
-   libsecret
+@@ -15,8 +15,8 @@
    libvncserver
    libxkbcommon
    pipewire
 -  systemd
    tpm2-tss
++  wireplumber
  )
  makedepends=(
-@@ -25,13 +22,16 @@
-   meson
- )
- groups=(gnome)
- prepare() {
-   cd $pkgname
+   asciidoc
+@@ -30,8 +30,9 @@
  }
  build() {
    local meson_options=(
-     -D vnc=true
 +    -D systemd=false
+     -D vnc=true
    )
 -  arch-meson $pkgname build "${meson_options[@]}"
 +  artix-meson $pkgname build "${meson_options[@]}"
    meson compile -C build
  }
-+_
diff --git a/world/diffs/mutter.diff b/world/diffs/mutter.diff
--- a/world/diffs/mutter.diff
+++ b/world/diffs/mutter.diff
@@ -1,54 +1,9 @@
 --- Arch PKGBUILD
 +++ Artix PKGBUILD
-@@ -4,7 +4,7 @@
-   mutter
-   mutter-docs
- )
--pkgver=45.0
-+pkgver=44.3
- pkgrel=1
- pkgdesc="Window manager and compositor for GNOME"
- url="https://gitlab.gnome.org/GNOME/mutter"
-@@ -17,11 +17,8 @@
-   gnome-settings-daemon
-   graphene
-   gsettings-desktop-schemas
--  iio-sensor-proxy
-   lcms2
-   libcanberra
--  libdisplay-info
--  libei
-   libgudev
-   libinput
-   libsm
-@@ -45,12 +42,11 @@
-   xorg-server-xvfb
- )
- checkdepends=(
--  gnome-session
-   python-dbusmock
-   wireplumber
-   zenity
- )
--_commit=4f6c91847088d7d6476b88575b3a6601b819b443  # tags/45.0^0
-+_commit=99d83f2985483bc192e1271665c442c7c480a588  # tags/44.3^0
- source=(
-   "git+https://gitlab.gnome.org/GNOME/mutter.git#commit=$_commit"
- )
-@@ -63,6 +59,8 @@
- 
- prepare() {
-   cd mutter
-+
-+  git cherry-pick -n '5a83e8ef8250526a40e8e69c^..d65883e0d7d70987e3888b86'
- }
- 
- build() {
-@@ -70,29 +68,37 @@
-     -D docs=true
+@@ -71,13 +71,14 @@
      -D egl_device=true
      -D installed_tests=false
--    -D libdisplay_info=true
+     -D libdisplay_info=true
 +    -D systemd=false
      -D wayland_eglstream=true
    )
@@ -61,74 +16,25 @@
    meson compile -C build
  }
  
--check() (
-+_check() (
-   export XDG_RUNTIME_DIR="$PWD/rdir" GSETTINGS_SCHEMA_DIR="$PWD/build/data"
-   mkdir -p -m 700 "$XDG_RUNTIME_DIR"
-   glib-compile-schemas "$GSETTINGS_SCHEMA_DIR"
+@@ -91,7 +92,7 @@
  
--  export NO_AT_BRIDGE=1 GTK_A11Y=none
--  export MUTTER_DEBUG_DUMMY_MODE_SPECS="800x600@10.0"
-+  pipewire &
-+  _p1=$!
- 
--  xvfb-run -s '-nolisten local +iglx -noreset' \
--    mutter/src/tests/meta-dbus-runner.py --launch=pipewire --launch=wireplumber \
+   xvfb-run -s '-nolisten local +iglx -noreset' \
+     mutter/src/tests/meta-dbus-runner.py --launch=pipewire --launch=wireplumber \
 -    meson test -C build --print-errorlogs -t 5 --setup plain
-+  wireplumber &
-+  _p2=$!
-+
-+  trap "kill $_p1 $_p2; wait" EXIT
-+
-+  meson test -C build --print-errorlogs -t 3 ||: #one test fails; just skip
++    meson test -C build --print-errorlogs -t 5 --setup plain ||: #one test fails; just skip
  )
-+
-+check() {
-+  dbus-run-session xvfb-run -s '-nolisten local +iglx -noreset' \
-+    bash -c "$(declare -f _check); _check"
-+}
  
  _pick() {
-   local p="$1" f d; shift
-@@ -105,7 +111,7 @@
- }
- 
- package_mutter() {
--  provides=(libmutter-13.so)
-+  provides=(libmutter-12.so)
- 
-   meson install -C build --destdir "$pkgdir"
- 
 
 
 ############# Stripped diff below #################
 
 --- Arch PKGBUILD
 +++ Artix PKGBUILD
-@@ -10,11 +10,8 @@
-   gnome-settings-daemon
-   graphene
-   gsettings-desktop-schemas
--  iio-sensor-proxy
-   lcms2
-   libcanberra
--  libdisplay-info
--  libei
-   libgudev
-   libinput
-   libsm
-@@ -39,19 +36,30 @@
- )
- prepare() {
-   cd mutter
-+  git cherry-pick -n '5a83e8ef8250526a40e8e69c^..d65883e0d7d70987e3888b86'
- }
- build() {
-   local meson_options=(
-     -D docs=true
+@@ -46,11 +46,12 @@
      -D egl_device=true
      -D installed_tests=false
--    -D libdisplay_info=true
+     -D libdisplay_info=true
 +    -D systemd=false
      -D wayland_eglstream=true
    )
@@ -137,16 +43,5 @@
 -  arch-meson mutter build "${meson_options[@]}"
 +  artix-meson mutter build "${meson_options[@]}"
    meson compile -C build
-+}
-+_
-+_pick() {
-+  local p="$1" f d; shift
-+  for f; do
-+    d="$srcdir/$p/${f#$pkgdir/}"
-+    mkdir -p "$(dirname "$d")"
-+    mv "$f" "$d"
-+    rmdir -p --ignore-fail-on-non-empty "$(dirname "$f")"
-+  done
  }
  package_mutter-docs() {
-   pkgdesc+=" (documentation)"
