2023-10-21 15:25:45+01:00

diff --git a/world/diffs/mutter.diff b/world/diffs/mutter.diff
--- a/world/diffs/mutter.diff
+++ b/world/diffs/mutter.diff
@@ -49,7 +49,7 @@
 
 --- Arch PKGBUILD
 +++ Artix PKGBUILD
-@@ -34,11 +34,12 @@
+@@ -38,11 +38,12 @@
      -D egl_device=true
      -D installed_tests=false
      -D libdisplay_info=true
@@ -62,4 +62,13 @@
 +  artix-meson mutter build "${meson_options[@]}"
    meson compile -C build
  }
- package_mutter-docs() {
+ check() (
+@@ -53,7 +54,7 @@
+   export MUTTER_DEBUG_DUMMY_MODE_SPECS="800x600@10.0"
+   xvfb-run -s '-nolisten local +iglx -noreset' \
+     mutter/src/tests/meta-dbus-runner.py --launch=pipewire --launch=wireplumber \
+-    meson test -C build --print-errorlogs -t 5 --setup plain
++    meson test -C build --print-errorlogs -t 5 --setup plain ||: #one test fails; just skip
+ )
+ _pick() {
+   local p="$1" f d; shift
